#mysql redis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_homework?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: zhlzlml
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9000

